@HOST = http://localhost:8888
@AUTH_TOKEN = Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiaWF0IjoxNjA3MzE1MDg2LCJleHAiOjIwODA2NzkwODZ9.cDPTTv6nN8z5PwBQh4EeYGGvO0rFxb_TR9wReFedtHo
@REFRESH_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZ1b25nLmRhbmdAZG5hLnZuIiwiX2lkIjoiNWZhZmFkYjgzMzRlZTkyZjQ0MmQ3YTNjIiwiaWF0IjoxNjA3MTUzNTUwfQ.fV8rHnccYt00PdHI4IFllRkD97bLI758Cu69HHacwj8

POST {{HOST}}/api/login
Content-Type: application/json

{
    "email": "vuong.dang@dna.vn"
}

####

GET {{HOST}}/api/get-user-info
Authorization: {{AUTH_TOKEN}}


###

GET {{HOST}}/api/user?page=20&limit=20
Authorization: {{AUTH_TOKEN}}

###

POST {{HOST}}/api/refresh-token
Content-Type: application/json

{
    "refreshToken": "{{REFRESH_TOKEN}}",
  "email": "vuong.dang@dna.vn"
}



################ Course ######################
GET {{HOST}}/rest/elearning_course
Authorization: {{AUTH_TOKEN}}

###

GET {{HOST}}/rest/elearning_course/5fcb86fdaf182d279c23428e
Authorization: {{AUTH_TOKEN}}


###


POST {{HOST}}/rest/elearning_course
Authorization: {{AUTH_TOKEN}}
Content-Type: application/json

{
   "title":"CFD2 Căn Bản",
   "teacher":"5fcddc6f64288113ec595f3e",
   "cover":"https://www.cfdtraining.vn/uploads/course/khoa-hoc-front-end-can-ban-cfd2.jpg",
   "price":4000000,
   "short_content":"Khóa học thực chiến dự án gồm HTML, CSS, CSS3, SCSS, Responsive với Media Query, Boostrap 4, Grunt, JS, jQuery.",
   "description":"Bạn đang là sinh viên, người đi làm hoặc từ ngành khác chuyển qua đang theo đuổi nghề Front-End Developer và đã từng học HTML, CSS, thậm chí là Javascript, nhưng chưa có cơ hội thực chiến dự án thực tế Website Responsive theo bảng thiết kế hoàn chỉnh, tư duy về animation, cấu trúc thư mục dự án, tối ưu tốc độ website, cũng như quy trình phân tích và triển khai dự án thực tế, thì khóa học CFD Căn Bản là sự lựa chọn phù hợp nhất dành cho bạn.",
   "open_date":1601251200000,
   "date_count":18,
   "close_date":1601251200000,
   "status":"finish",
   "type":"offline",
   "content":[
      
   ],
   "required":[
      "Có laptop cá nhân",
      "Cài đặt phần mềm Photoshop, Adobe illustrator, Skype, VS Code hoặc Sublime Text",
      "Hạn chế tối đa nghỉ học và phài hoàn thành bài tập được giao.",
      "Thành viên CFD phải có tinh thần chiến đấu, trách nhiệm và chủ động cao trong việc học ở văn phòng, cũng như tự học và làm thêm tại nhà."
   ],
   "formula":[
      "Học offline với sự hướng dẫn của 4 mentor tại văn phòng CFD.",
      "Dạy và thực hành thêm bài tập online thông qua Skype.",
      "Hỗ trợ từ xa thông qua Teamviewer hoặc Ultraview",
      "Được các mentor và các bạn trong team CFD hỗ trợ thông qua group Facebook CFD"
   ],
   "schedule":{
      "start":1601251200000,
      "time":"Thứ 2 từ 18h45-21h45, Thứ 3 từ 18h45-21h45, Thứ 6 từ 18h45-21h45"
   },
   "mentor":[
      "5fbd0ddf72696c37ac1f0563",
      "5fcddc9e64288113ec595f3f",
      "5fcddcd464288113ec595f40"
   ]
}

# {
#    "title":"CFD2 React JS",
#    "teacher":"5fbd0ddf72696c37ac1f0563",
#    "cover":"https://www.cfdtraining.vn/uploads/course/khoa-hoc-react-js-javascript-cfd3.jpg",
#    "price":6000000,
#    "short_content":"Khóa học thực chiến dự án thực tế gồm Javascript nâng cao, ES6, JSON, API và React JS.",
#    "description":"Nếu bạn đã có kiến thức cơ bản về lập trình Website Responsive hoặc đã học qua khóa CFD Căn Bản, bạn muốn muốn có nhiều cơ hội để ứng tuyển vào vị trí Front-End Developer thì React JS là thư viện javascript được các công ty yêu cầu nhiều nhất hiện nay. Khóa React JS tại CFD sẽ hướng dẫn bạn có được kiến thức và kỹ năng quan trọng để đi làm dựa trên thực hành dự án thực tế xuyên suốt khóa học.",
#    "open_date":1601251200000,
#    "date_count":18,
#    "close_date":1601251200000,
#    "status":"finish",
#    "type":"offline",
#    "content":[
      
#    ],
#    "required":[
#       "Có kiến thức cơ bản về lập trình, có thể cắt giao diện từ bản thiết kế",
#       "Có kiến thức tốt về Javascript, ES6, ES7,....",
#       "Hiểu biết về Web Service và API",
#       "Cài đặt phần mềm VSCode, Photoshop, Skype, Teamviewer"
#    ],
#    "formula":[
#       "Học offline tại văn phòng CFD.",
#       "Dạy và thực hành thêm bài tập online thông qua Skype.",
#       "Hỗ trợ trực tuyến thông qua Teamviewer hoặc Ultraview",
#       "Được các mentor và các bạn trong team CFD hỗ trợ thông qua group CFD Facebook"
#    ],
#    "schedule":{
#       "start":1601251200000,
#       "time":"Thứ 2 từ 18h45-21h45, Thứ 3 từ 18h45-21h45, Thứ 6 từ 18h45-21h45"
#    },
#    "mentor":[
#       "5fcddc9e64288113ec595f3f"
#    ]
# }

################ Teacher ######################
GET {{HOST}}/rest/elearning_teacher
Authorization: {{AUTH_TOKEN}}


###
POST {{HOST}}/rest/elearning_teacher
Authorization: {{AUTH_TOKEN}}

{
  
}