@HOST = http://localhost:8888
@AUTH_TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiaWF0IjoxNjA3MzE1MDg2LCJleHAiOjIwODA2NzkwODZ9.cDPTTv6nN8z5PwBQh4EeYGGvO0rFxb_TR9wReFedtHo
@REFRESH_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZ1b25nLmRhbmdAZG5hLnZuIiwiX2lkIjoiNWZhZmFkYjgzMzRlZTkyZjQ0MmQ3YTNjIiwiaWF0IjoxNjA3MTUzNTUwfQ.fV8rHnccYt00PdHI4IFllRkD97bLI758Cu69HHacwj8
@FOREVER_TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiaWF0IjoxNjA3MzE1MDg2LCJleHAiOjIwODA2NzkwODZ9.cDPTTv6nN8z5PwBQh4EeYGGvO0rFxb_TR9wReFedtHo


#####
POST {{HOST}}/rest/ecommerce_product
Authorization: {{FOREVER_TOKEN}}
Content-Type: application/json

{
   "sku":"F00003",
   "stock":true,
   "fresh":120,
   "delivery_day":1,
   "name":"Điện Thoại iPhone 11 64GB - Hàng Chính Hãng",
   "image":[],
   "specifications": "",
   "price":"626000",
   "currency":"vnđ",
   "main_description":"",
   "reviews":[
      {
         "comment":"Sản phẩm dùng rất tốt",
         "star":5
      },
      {
         "comment":"Tươi ngon",
         "star":5
      }
   ],
   "star":5,
   "faq":[
      
   ],
   "store":"5ff2d67a223c8c18c83c4395",
   "brand":"5ff2c65663a9610bd85836ab",
   "category":"5ff2dd3b39b8f02c54ef9b1d"
}